kind: deployment
metadata:
  name: nginx-deployment-2
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      container:
      - name: nginx
        image: nginx:1.12.2
        ports: 90
